# base image
FROM node:19.4.0-alpine as build

# args
ARG app
ARG mode

# create app directory
RUN mkdir /app
WORKDIR /app

# add source files
ADD . /app

# install dependencies
RUN npm install

# env
ENV PATH /app/node_modules/.bin:$PATH

# switch to source directory
WORKDIR /app/webs/${app}

# build
#RUN cp config-env/.env.k8slocal config/env/.env.production
RUN vite build --config ../../vite.web.config.js --mode ${mode}

# runtime image
FROM nginx:1.23.3-alpine

# args
ARG app

# copy build files
COPY --from=build /app/webs/${app}/dist /usr/share/nginx/html
