apiVersion: v1
kind: Namespace
metadata:
  name: starting-again
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qpp-ingress
  namespace: starting-again
  annotations:   
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  defaultBackend:
    service:
      name: api-1
      port:
        number: 3000
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-1
            port:
              number: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-1
  namespace: starting-again
  labels:
    app: api-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-1
  template: 
    metadata: 
      labels:
        app: api-1
    spec:
      containers:
      - name: api-1
        image: api-1:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: api-1
  namespace: starting-again
spec:
  selector:
    app: api-1
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-2
  namespace: starting-again
  labels:
    app: api-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-2
  template: 
    metadata: 
      labels:
        app: api-2
    spec:
      containers:
      - name: api-2
        image: api-2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: api-2
  namespace: starting-again
spec:
  selector:
    app: api-2
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000