version: "3.4"

services:
  db:
    image: mongo:latest
    restart: always
    networks:
      - webnet
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=B49B817164814B2BBDCCC0C5674BFDB3
      - MONGO_INITDB_ROOT_PASSWORD=DBD2ED7937D44982A483243E1C49995E95F147A3F0A94997A13288A9C6F7377DB4E1BFAAACB44F2285517816A8222B576

  api-1:
    image: node:19.4.0-alpine
    volumes:
      - ../:/app
    depends_on: [db]
    networks:
      - webnet
    env_file:
      - api.env
    environment:
      - NODE_ENV=development
    working_dir: /app/apis/api-1
    command: npx vite --config ../../_config-vite/vite.node.config.js

  api-2:
    image: node:19.4.0-alpine
    volumes:
      - ../:/app
    depends_on: [db]
    networks:
      - webnet
    env_file:
      - api.env
    environment:
      - NODE_ENV=development
    working_dir: /app/apis/api-2
    command: npx vite --config ../../_config-vite/vite.node.config.js
      
  graphql-server:
    image: node:19.4.0-alpine
    volumes:
      - ../:/app
    depends_on: [db]
    networks:
      - webnet
    env_file:
      - api.env
    environment:
      - NODE_ENV=development
    working_dir: /app/apis/graphql-server
    command: npx vite --config ../../_config-vite/vite.node.config.js

  web-1:
    image: node:19.4.0-alpine
    volumes:
      - ../:/app
    depends_on: [db, api-1, api-2, graphql-server]
    networks:
      - webnet
    ports:
      - 5173:5173
    environment:
      - PORT=5173
      - NODE_ENV=development
    working_dir: /app/webs/web-1
    command: npx vite --config ../../_config-vite/vite.web.config.js

networks:
  webnet:
