# base image
FROM starting-again-base:latest as build

# args
ARG app
ARG mode

# switch to source directory
WORKDIR /app/webs/${app}

# build
RUN vite build --config ../../_config-vite/vite.web.config.js --mode ${mode}

# runtime image
FROM nginx:1.23.3-alpine

# args
ARG app

# copy build files
COPY --from=build /app/webs/${app}/dist /usr/share/nginx/html
