# base image
FROM node:19.4.0-alpine as build

# create app directory
RUN mkdir /app
WORKDIR /app

# add source files
ADD . /app

# install dependencies
RUN npm install

# env
ENV PATH /app/node_modules/.bin:$PATH