# base image
FROM starting-again-base:latest as build

# args
ARG app

# switch to source directory
WORKDIR /app/apis/${app}

# build
RUN esbuild src/server.js --platform=node --bundle --minify --outfile=dist/index.js

# runtime image
FROM node:19.4.0-alpine

# args
ARG app

# create app directory
RUN mkdir /app
WORKDIR /app

# copy build files
COPY --from=build /app/apis/${app}/dist .

# expose port
EXPOSE 3000:3000

# run the server when the container starts
CMD node index.js
