# base image
FROM starting-again-base:latest as build

# args
ARG app

# switch to source directory
WORKDIR /app/webs/${app}

# build the web
RUN vite build --config ../../_config-vite/vite.web.config.js

# build the server
RUN esbuild src/server.ts --platform=node --bundle --minify --outfile=dist/index.js

# runtime image
FROM node:19.4.0-alpine

# create app directory
RUN mkdir /app
WORKDIR /app

# args
ARG app

# copy build files
COPY --from=build /app/webs/${app}/dist /app

# run the server when the container starts
CMD node index.js
