# base image
FROM node:19.4.0-alpine

#install bash and nodemon
RUN apk add --no-cache bash
RUN npm install -g nodemon

# create app directory
RUN mkdir /app
WORKDIR /app

# expose port
EXPOSE 3000:3000
