name: web 2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      working-directory: ./webs/web-2
    - name: docker build
      run: docker build -f Dockerfile.web --build-arg app=web-2 --build-arg mode=k8slocal -t web-2 .        
